### ISSUE TITLE
Fibaro FGRGBWM-441 - add channel: Color_Raw

### ISSUE THREAD

**Issue by pogo0** [openhab/org.openhab.binding.zwave#1891]
I'd love if someone could add Color_Raw to database for Fibaro first generation RGBW controller (Fibaro FGRGBWM-441) just like it already is in Fibaro FGRGBWM-442 (second generation)
I added it manually to _fgrgbw_0_0.xml_ file with code:
`<channel id="color_raw1" typeId="color_raw">`
`      <label>Color Raw</label>`
`      <properties>`
`          <property name="binding:*:StringType">COMMAND_CLASS_SWITCH_COLOR</property>`
`      </properties>`
`</channel>`
and it just works. I hope it can be a standard feature for this controller.

I hope my explanation makes it easy to implement.

**Comment by apella12** [comment]
The ZW DB is community maintained/updated and then reviewed by the developer/maintainer.  There is a blog that explains the process here. [https://www.opensmarthouse.org/blog/](url) 
I did take a look at the two devices and the color CC is only on the root (EP 0) for the 441.  The color_raw channel and Color CC is on EP 1 for the 442 device. Since your manual update works, adding the color_raw to the root color CC should also work.
