### ISSUE TITLE
Add configuration parameter option for Qubino Dimmer

### ISSUE THREAD

**Issue by mplutka** [openhab/org.openhab.binding.zwave#793]
* OH2 Version: 2.2.0

If the problem is associated with a device, please provide the following -:

* Device name: ZMNHDD Flush Dimmer Plus
* Thing type id: qubino_zmnhdd_00_000

Config item 20 has a third option, so the available options should look like this:
`        <options>
          <option value="0">0 - single push button (connected to I1)</option>
          <option value="1">1 - 3-way switch (connected to I1 and I2)</option>
          <option value="2">2 - Additional switch connected to I2</option>
        </options>
`

**Comment by cdjackson** [comment]
Hi,
That doesn't appear to be what the manual states - at least not the version that is currently in the database (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/210). Maybe this is for a later version of the firmware?

Please can you update this on the database site. If there is a newer version of the firmware that has this option, then it should be fine to just add this extra option, but please also upload the latest manual so that it's consistent.

Thanks
Chris

**Comment by mplutka** [comment]
Hi, 
I don't have edit rights for the database but there is indeed a new version of the firmware/manual available (1.9): http://qubino.com/download/990/

Thanks
Markus

**Comment by openhab-5iver** [comment]
@mplutka, I will add this configuration parameter for you, but could you please check to see if this is the only change in the newer firmware?

**Comment by mplutka** [comment]
I can't see any other changes to configuration parameters than the one I
mentioned.

2018-01-05 18:25 GMT+01:00 Scott Rushworth <notifications@github.com>:

**Comment by openhab-5iver** [comment]
OK... thank you for checking.

**Comment by cdjackson** [comment]
> I don't have edit rights for the database

I've updated this.

@openhab-5iver thanks for supporting.

**Comment by cdjackson** [comment]
It looks like the update is done so I'll close this. I'll probably do an update to the binding tomorrow.
