### ISSUE TITLE
[Feature request] NGD00Z alarm_raw and BARRIER_OPERATOR channels

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/org.openhab.binding.zwave#808]
@cdjackson 

1. The [NGD00Z](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/11) in the database had 16 channels under the ALARM CC. I had removed these, because it it does not support the ALARM CC. But now I know better... this device supports the NOTIFICATION CC, as required by the specification for BARRIER_OPERATOR. Before adding this back in, it looks like this may be another good place for an aggregated alarm_raw channel, like was done for locks. The comments from Ash Gupta in the device database entry list some of the values, but I can't personally confirm them. Personally, I'm interested in the low battery notification.

2. Lastly, the BARRIER_OPERATOR (and barrier_state channel) are difficult to work with. It requires [a Number item, Switch item, and a rule](https://community.openhab.org/t/openhab2-and-linear-ngd00z-4-garage-door-controller/26154/52?u=5iver) in order to open/close the garage door, and to update the state of the switch item if the door is operated manually. Do you have any thoughts/plans on how/if this functionality could be implemented in the binding, or would this be too device specific to include in the binding? I'm not familiar with any other devices that use BARRIER_OPERATOR and if having something like this in the binding would benefit them too. What I can envision for this device are a read-only String channel for reporting the current state of the door (open, opening, stopped, closing, closed), a read/write Switch channel to control opening/closing but which would also be updated by the state of the door (OFF in all cases except closed), and another read-only String channel for notifications (like alarm_raw... requested in number 1). A discussion blipped up [on the forum](https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653/2069?u=5iver) at least once about this.

If you prefer, I can copy this to a forum post to get more feedback from the community... or split this into multiple issues.

**Comment by cdjackson** [comment]
I suggest to split these issues. For the first one, let's deal with each notification separately - ie if you want the battery warnings, then please open an issue for the battery warnings and I'll add it. I'm not sure that the RAW channel is the best here, and I think in many/most cases I'd prefer to have separate notifications, but it should be available now anyway - ie there's nothing to stop you using that with any device - it's not limited to door locks.

For the second part I don't have an answer at the moment - mostly because I don't understand the command class. Can you open an issue for this and we can discuss - if possible, please provide a summary of how it works - maybe cut and paste part of a forum discussion so we have a starting point.

I'll close this and await your new issues :) .
