### ISSUE TITLE
Textual Thing stays in INITIALIZING status

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/org.openhab.binding.zwave#832]
When creating a Z-Wave Thing via DSL like
```
zwave:fibaro_fgd212_03_005:test "My Test Device"
```
the Thing stays in INITIALIZING status forever. Instead, the handler is expected to set the status to UNKNOWN, ONLINE or OFFLINE immediately.

**Comment by cdjackson** [comment]
I think the reason for this is that the required configuration is not set - ie you have not set the node ID. I expected that the system would not call the handler initialize() if this wasn't set, but it seems that's not the case here.

I think the reason is that the startup is checking the configuration for the ```thing-type``` and my config handler is providing configuration for the ```thing``` so it misses this check.

I'll look to update the config provider to always provide required config descriptions for the ```thing-type```.

**Comment by kaikreuzer** [comment]
> I think the reason is that the startup is checking the configuration for the thing-type and my config handler is providing configuration for the thing so it misses this check.

If this is really the case, you should definitely enter a bug for the ESH ThingManager about this! //cc @sjka

**Comment by cdjackson** [comment]
I've opened and issue (https://github.com/eclipse/smarthome/issues/5180). For now at least, to get around this I'm handling ```thing-type``` configuration in my config provider as well as ```thing``` configuration.
